//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PositivityZone {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PositivityZone.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string buttonAnswer {
            get {
                return ResourceManager.GetString("buttonAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string buttonModerate {
            get {
                return ResourceManager.GetString("buttonModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string buttonNo {
            get {
                return ResourceManager.GetString("buttonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string buttonPassword1 {
            get {
                return ResourceManager.GetString("buttonPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string buttonPassword2 {
            get {
                return ResourceManager.GetString("buttonPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        internal static string buttonRecover {
            get {
                return ResourceManager.GetString("buttonRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string buttonReturn {
            get {
                return ResourceManager.GetString("buttonReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string buttonSend {
            get {
                return ResourceManager.GetString("buttonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string buttonSkip {
            get {
                return ResourceManager.GetString("buttonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent.
        /// </summary>
        internal static string buttonVent {
            get {
                return ResourceManager.GetString("buttonVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string buttonYes {
            get {
                return ResourceManager.GetString("buttonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer.
        /// </summary>
        internal static string labelAnswer {
            get {
                return ResourceManager.GetString("labelAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string labelLanguage {
            get {
                return ResourceManager.GetString("labelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it appropiate?.
        /// </summary>
        internal static string labelModerate {
            get {
                return ResourceManager.GetString("labelModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t posted anything..
        /// </summary>
        internal static string labelNoUserEntries {
            get {
                return ResourceManager.GetString("labelNoUserEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string labelOptions {
            get {
                return ResourceManager.GetString("labelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positivity Zone.
        /// </summary>
        internal static string labelTitle {
            get {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UID:.
        /// </summary>
        internal static string labelUIDInfo {
            get {
                return ResourceManager.GetString("labelUIDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s on your mind?.
        /// </summary>
        internal static string labelVent {
            get {
                return ResourceManager.GetString("labelVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent.
        /// </summary>
        internal static string labelVent2 {
            get {
                return ResourceManager.GetString("labelVent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string labelVersion {
            get {
                return ResourceManager.GetString("labelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer:.
        /// </summary>
        internal static string textAnswer {
            get {
                return ResourceManager.GetString("textAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered: .
        /// </summary>
        internal static string textAnswered {
            get {
                return ResourceManager.GetString("textAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Couldn&apos;t send your answer..
        /// </summary>
        internal static string textAnswerError {
            get {
                return ResourceManager.GetString("textAnswerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can answer on vents that other people posted. Please remember to follow the rules:
        ///- no personal details
        ///- full anonymity
        ///- no toxicity
        ///- no profanity.
        /// </summary>
        internal static string textAnswerInfo {
            get {
                return ResourceManager.GetString("textAnswerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer has been sent. It is awaiting approval. Thank you!.
        /// </summary>
        internal static string textAnswerSuccess {
            get {
                return ResourceManager.GetString("textAnswerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You checked and approved an entry!.
        /// </summary>
        internal static string textApproved {
            get {
                return ResourceManager.GetString("textApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You checked and disapproved an entry!.
        /// </summary>
        internal static string textDisapproved {
            get {
                return ResourceManager.GetString("textDisapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent ID: .
        /// </summary>
        internal static string textEntry {
            get {
                return ResourceManager.GetString("textEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string textError {
            get {
                return ResourceManager.GetString("textError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your safe space. You can express your feelings, give advices and enforce the rules!.
        /// </summary>
        internal static string textFirstLaunch {
            get {
                return ResourceManager.GetString("textFirstLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing to moderate! Come back later..
        /// </summary>
        internal static string textModerate {
            get {
                return ResourceManager.GetString("textModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your job is to check if vents and answers follow the rules:
        ///- no personal details
        ///- full anonymity
        ///- no toxicity
        ///- no profanity
        ///Be responsible. Decide the fate of the entry only when you&apos;re certain..
        /// </summary>
        internal static string textModerateInfo {
            get {
                return ResourceManager.GetString("textModerateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. Something went wrong and we couldn&apos;t send your approval/disapproval..
        /// </summary>
        internal static string textModError {
            get {
                return ResourceManager.GetString("textModError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string textNo {
            get {
                return ResourceManager.GetString("textNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no vents to answer. Come back later..
        /// </summary>
        internal static string textNoVents {
            get {
                return ResourceManager.GetString("textNoVents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read!.
        /// </summary>
        internal static string textRead {
            get {
                return ResourceManager.GetString("textRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules:
        ///- no personal details
        ///- full anonymity
        ///- no toxicity
        ///- no profanity.
        /// </summary>
        internal static string textRules {
            get {
                return ResourceManager.GetString("textRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string textSuccess {
            get {
                return ResourceManager.GetString("textSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some rules that you must obey:
        ///- no personal details
        ///- full anonymity
        ///- no toxicity
        ///- no profanity
        ///You&apos;ll need to wait for your vent to be approved by someone else. If you don&apos;t follow the rules, you will get banned..
        /// </summary>
        internal static string textVentInfo {
            get {
                return ResourceManager.GetString("textVentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string textYes {
            get {
                return ResourceManager.GetString("textYes", resourceCulture);
            }
        }
    }
}
